project:
  type: website
  output-dir: docs
  
website: 
  title: PPLS 2026
  description: Prepared hands save tiny lives
  navbar:
    background: "#222322"
    foreground: "#FFFFFF"
    title: PPLS 2026
    right:
      - text: ""
        href: index.qmd
        icon: house-door-fill
      - text: Registration
        href: registration.qmd 
      - text: Schedule
        href: schedule.qmd
      - text: Venue Direction
        href: direction.qmd
  page-footer:
    left: PPLS 2026 at UM
    
    
