---
title: "Venue & Directions"
subtitle: "PPLS 2026 | Universiti Malaya Medical Centre"
---

## Location

The workshop will be held at the **Universiti Malaya Medical Centre (UMMC)**

### Address:
**Wad Peperiksaan A** Level 3, <br>
Menara Timur (East Tower), 
Universiti Malaya Medical Centre  
59100 Kuala Lumpur, Malaysia

### Google Location: 
https://maps.app.goo.gl/Bj3b7AmCHvss2tSFA


## Getting to UMMC

### 🚗 By Car
Universiti Malaya Medical Centre is easily accessible via the **Federal Highway**. 

* **Navigation:** Search for "Menara Timur UMMC" on Google Maps or Waze.
* **Parking:** 
    * **Menara Timur Carpark** (Closest to the venue)
    * **Complex Parkir Bertingkat:** Multi-storey parking located near the main hospital entrance.
  
### 🚇 By Public Transport (LRT)
The train station nearby UMMC are **LRT Universiti** (Kelana Jaya Line) and **LRT Taman Jaya**.

* **Taxi/Grab:** From the station to the East Tower (Menara Timur) entrance.

## Finding the Workshop Room

Once you arrive at **Menara Timur (East Tower)**:

1.  Enter through the main sliding doors of the East Tower.
2.  Locate the **East Tower Lift Lobby**.
3.  Take the elevator to **Level 3**.
4.  Follow the directional signs placed in the hallway for **"PPLS Workshop - Wad Peperiksaan A"**.




